// Author: Subash Karki
// setup-merge.test.js — phantom_merge_config (setup.sh): fresh write,
// preserve-existing byte-for-byte, append missing sections, ensure models.sage.
// Zero external deps: node:test + node:assert only.
'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const SETUP_SH = path.join(__dirname, '..', 'setup.sh');

// Mirrors the heredoc setup.sh generates (values are irrelevant to merge logic).
const GENERATED = `# Phantom Works — User Configuration
# Generated by setup.sh on 2026-06-09

jira:
  project: "CP"
  auto_transition: true

slack:
  dm_channel: ""
  enabled: false

models:
  sage: fable

integrations:
  atlassian_mcp: false
  greptile: false

preferences:
  auto_draft_pr: true
  caveman_output: true
`;

function mkTmp() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'setup-merge-'));
}

// Sources setup.sh in function-only mode and runs the merge against
// $PHANTOM_DATA/config.yaml. Returns stdout + target path.
function runMerge(dataDir, generatedContent) {
  const gen = path.join(dataDir, 'generated.yaml');
  fs.writeFileSync(gen, generatedContent);
  const target = path.join(dataDir, 'config.yaml');
  const out = execFileSync(
    'bash',
    ['-c', 'source "$1"; phantom_merge_config "$2" "$3"', 'merge-runner', SETUP_SH, gen, target],
    {
      env: { ...process.env, PHANTOM_SETUP_SOURCE_ONLY: '1', PHANTOM_DATA: dataDir },
      encoding: 'utf8',
    }
  );
  return { out, target };
}

test('fresh install: writes full generated config including models.sage', () => {
  const tmp = mkTmp();
  try {
    const { out, target } = runMerge(tmp, GENERATED);
    const written = fs.readFileSync(target, 'utf8');
    assert.equal(written, GENERATED);
    assert.match(written, /^models:$/m);
    assert.match(written, /^ {2}sage: fable$/m);
    assert.match(out, /Config written to /);
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});

test('existing config with user-modified values is preserved byte-for-byte', () => {
  const tmp = mkTmp();
  try {
    const existing = `# my config — hand-tuned

jira:
  project: "CUSTOM"
  auto_transition: false

slack:
  dm_channel: "D123"
  enabled: true

models:
  sage: opus

integrations:
  greptile: true

preferences:
  auto_draft_pr: false
`;
    fs.writeFileSync(path.join(tmp, 'config.yaml'), existing);
    const { out, target } = runMerge(tmp, GENERATED);
    assert.equal(fs.readFileSync(target, 'utf8'), existing);
    assert.match(out, /Existing config preserved/);
    assert.match(out, /nothing to add/);
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});

test('existing config missing models: section gains it, rest untouched', () => {
  const tmp = mkTmp();
  try {
    const existing = `jira:
  project: "CUSTOM"

slack:
  dm_channel: ""
  enabled: false

integrations:
  greptile: true

preferences:
  auto_draft_pr: false
`;
    fs.writeFileSync(path.join(tmp, 'config.yaml'), existing);
    const { out, target } = runMerge(tmp, GENERATED);
    const merged = fs.readFileSync(target, 'utf8');
    // Append-only merge: original content stays a byte-exact prefix.
    assert.ok(merged.startsWith(existing));
    assert.match(merged, /^models:$/m);
    assert.match(merged, /^ {2}sage: fable$/m);
    assert.equal(merged.match(/^jira:$/gm).length, 1);
    assert.match(out, /added missing: models/);
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});

test('existing models: section without sage key gains sage line in place', () => {
  const tmp = mkTmp();
  try {
    const existing = `jira:
  project: "CUSTOM"

models:
  blade: fable

preferences:
  auto_draft_pr: false
`;
    fs.writeFileSync(path.join(tmp, 'config.yaml'), existing);
    const { out, target } = runMerge(tmp, GENERATED);
    const merged = fs.readFileSync(target, 'utf8');
    assert.match(merged, /^models:\n {2}sage: fable\n {2}blade: fable$/m);
    // User values elsewhere untouched.
    assert.match(merged, /^ {2}project: "CUSTOM"$/m);
    assert.match(out, /models\.sage/);
    // Missing sections (slack, integrations) appended too.
    assert.match(merged, /^slack:$/m);
    assert.match(merged, /^integrations:$/m);
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
});
