#!/usr/bin/env bash
# Phantom Works — Setup Wizard
# Author: Subash Karki

set -euo pipefail

TEAM_DIR="$HOME/.claude/team"
COMMANDS_LINK="$HOME/.claude/commands/team"

echo ""
echo "  Phantom Works — Agent Crew Setup"
echo "  ─────────────────────────────────"
echo ""

# 1. Symlink
if [ -L "$COMMANDS_LINK" ] || [ -d "$COMMANDS_LINK" ]; then
  echo "  ✓ Symlink exists: $COMMANDS_LINK"
else
  ln -s "$TEAM_DIR/commands" "$COMMANDS_LINK"
  echo "  ✓ Created symlink: $COMMANDS_LINK → $TEAM_DIR/commands"
fi

# 2. Initialize directories
for dir in sessions events state learnings global/patterns; do
  mkdir -p "$TEAM_DIR/$dir"
  if [ ! -f "$TEAM_DIR/$dir/.gitkeep" ]; then
    touch "$TEAM_DIR/$dir/.gitkeep"
  fi
done
echo "  ✓ Directories initialized (sessions, events, state, learnings, global/patterns)"

# 3. Initialize learnings INDEX.md if empty
if [ ! -f "$TEAM_DIR/learnings/INDEX.md" ]; then
  cat > "$TEAM_DIR/learnings/INDEX.md" << 'INDEXEOF'
# Learnings Index

## Patterns

## Corrections

## Sessions
INDEXEOF
  echo "  ✓ Created learnings/INDEX.md"
fi

# 4. Configuration
echo ""
echo "  Configuration"
echo "  ─────────────"

# Jira project key
read -rp "  ? Jira project key (e.g., CP) [skip]: " JIRA_PROJECT
JIRA_PROJECT="${JIRA_PROJECT:-}"

# Slack DM channel
read -rp "  ? Slack DM channel ID for notifications [skip]: " SLACK_CHANNEL
SLACK_CHANNEL="${SLACK_CHANNEL:-}"

# Default Spark model
read -rp "  ? Default model for Spark agents (sonnet/haiku) [sonnet]: " SPARK_MODEL
SPARK_MODEL="${SPARK_MODEL:-sonnet}"

# 5. Auto-detect integrations
echo ""
echo "  Detecting integrations..."

ATLASSIAN_AVAILABLE="false"
if claude --print 2>/dev/null | grep -q "atlassian" 2>/dev/null; then
  ATLASSIAN_AVAILABLE="true"
  echo "  ✓ Atlassian MCP: detected"
else
  echo "  ○ Atlassian MCP: not found (Jira features disabled)"
fi

PHANTOM_AVAILABLE="false"
if claude --print 2>/dev/null | grep -q "phantom" 2>/dev/null; then
  PHANTOM_AVAILABLE="true"
  echo "  ✓ phantom-ai MCP: detected"
else
  echo "  ○ phantom-ai MCP: not found (graph features disabled)"
fi

SLACK_AVAILABLE="false"
if claude --print 2>/dev/null | grep -q "Slack" 2>/dev/null; then
  SLACK_AVAILABLE="true"
  echo "  ✓ Slack MCP: detected"
else
  echo "  ○ Slack MCP: not found (notifications disabled)"
fi

# 6. Write config
cat > "$TEAM_DIR/config.yaml" << CONFIGEOF
# Phantom Works — User Configuration
# Generated by setup.sh on $(date +%Y-%m-%d)

jira:
  project: "${JIRA_PROJECT}"
  auto_transition: true

slack:
  dm_channel: "${SLACK_CHANNEL}"
  enabled: ${SLACK_AVAILABLE}

models:
  spark: ${SPARK_MODEL}
  cortex: opus
  prism: opus
  sentinel: sonnet

integrations:
  atlassian_mcp: ${ATLASSIAN_AVAILABLE}
  phantom_ai: ${PHANTOM_AVAILABLE}
  slack_mcp: ${SLACK_AVAILABLE}
  greptile: false

preferences:
  auto_draft_pr: true
  caveman_output: true
  fun_fact_in_pr: false
CONFIGEOF
echo ""
echo "  ✓ Config written to $TEAM_DIR/config.yaml"

# 7. Prerequisites check
echo ""
echo "  Prerequisites"
echo "  ─────────────"

if command -v claude &>/dev/null; then
  echo "  ✓ Claude Code CLI"
else
  echo "  ✗ Claude Code CLI — install from https://claude.ai/code"
fi

if command -v gh &>/dev/null && gh auth status &>/dev/null 2>&1; then
  echo "  ✓ gh CLI (authenticated)"
else
  echo "  ○ gh CLI — install and run 'gh auth login' for PR features"
fi

echo ""
echo "  ─────────────────────────────────"
echo "  Ready! Run /team:start \"your task\" in any repo."
echo ""
echo "  Quick start:"
echo "    /team:start \"CP-41171\"          # with Jira ticket"
echo "    /team:start \"fix the auth bug\"  # free text"
echo "    /team:verify                    # run quality gate"
echo "    /team:pause                     # save & step away"
echo ""
